redditclone/config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  resources :subs, except: [:destroy]
  resources :comments, only: [:show, :create] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end


end

redditclone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :moderator, :description, presence: true
  validates :title, presence: true, uniqueness: true

  belongs_to :moderator,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: "User"

  has_many :post_subs,
  foreign_key: :sub_id,
  primary_key: :id,
  class_name: "PostSub"


  has_many :posts,
  through: :post_subs

end

redditclone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = current_user.subs.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title,:description,:user_id)
  end


end

redditclone/app/helpers/subs_helper.rb
module SubsHelper
end

redditclone/app/views/subs/edit.html.erb
<h1>Edit sub!</h1>

<form action="<%=sub_url%>" method="post">

  <%= auth_token %>

  <input type="hidden" name="_method" value="patch">

  <label>Title
    <input type="text" name="sub[title]">
  </label>

  <label>Description
    <input type="text" name="sub[description]">
  </label>

  <input type="submit">

</form>

redditclone/app/views/subs/index.html.erb
<%= link_to "Create a Sub!", new_sub_url %>


<h1>All Subs!</h1>
<ul>
  <%@subs.each do |sub|%>
  <li>
    <%=link_to sub.title, sub_url(sub)%>
  </li>
  <% end %>
</ul>

redditclone/app/views/subs/new.html.erb
<h1>Create a new sub!</h1>

<form action="<%=subs_url%>" method="post">

  <%= auth_token %>

  <label>Title
    <input type="text" name="sub[title]">
  </label>
  <br>
  <label>Description
    <input type="text" name="sub[description]">
  </label>
  <br>
  <input type="submit">

</form>

redditclone/app/views/subs/show.html.erb
<h1> <%=@sub.title%> </h1>
<h3> description </h3>
<%=@sub.description%>
<br></br>
<%= link_to "Make New Post!", new_post_url %>
<br>

<h3>Posts for <%=@sub.title%></h3>
<ul>
  <%@sub.posts.each do |post|%>
  <li>
    <%= post.votes.sum(:value) %>
    <%=link_to post.title, post_url(post)%>

  </li>
  <% end %>
</ul>

<% if current_user && current_user.id == @sub.user_id %>
  <%= link_to "Edit Sub", edit_sub_url %>
<% end %>