redditclone/config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  resources :subs, except: [:destroy]
  resources :comments, only: [:show, :create] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end


end

redditclone/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  user_id           :integer          not null
#  post_id           :integer          not null
#  content           :string           not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  parent_comment_id :integer
#

class Comment < ApplicationRecord
  validates :author, :content, :post, presence:true

  belongs_to :author,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: "User"

  belongs_to :post

  has_many :votes, as: :votable

  has_many :child_comments,
  primary_key: :id,
  foreign_key: :parent_comment_id,
  class_name: "Comment"

end

redditclone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :not_logged_in?

  def new
    @post_id = params[:post_id]
    render :new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def upvote
    @comment = Comment.find(params[:id])
    @comment.votes.create(value:1)
    redirect_to comment_url(@comment)
  end

  def downvote
    @comment = Comment.find(params[:id])
    @comment.votes.create(value:-1)
    redirect_to comment_url(@comment)
  end


  private

  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :content, :parent_comment_id)
  end
end

redditclone/app/helpers/comments_helper.rb
module CommentsHelper
end

redditclone/app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

redditclone/app/views/comments/new.html.erb
<h1>New Comment</h1>

<form action="<%=comments_url%>" method="post">
  <%= auth_token %>

  <input type="hidden" name="comment[post_id]" value="<%=@post_id%>">

  <label>Body
  <input type="text" name="comment[content]">
  </label>

  <input type="submit">

</form>

redditclone/app/views/comments/show.html.erb
<h3>Reply to this comment</h3>

<%= button_to "Upvote", upvote_comment_url %>
<%= button_to "Downvote", downvote_comment_url %>

<form action="<%=comments_url%>" method="post">
  <%= auth_token %>

  <input type="hidden" name="comment[post_id]" value="<%=@comment.post_id%>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%=@comment.id%>">

  <label>Body
  <input type="text" name="comment[content]">
  </label>

  <input type="submit">

</form>