redditclone/config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  resources :subs, except: [:destroy]
  resources :comments, only: [:show, :create] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end


end

redditclone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  content    :text
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, :author, :subs, presence: true

  has_many :post_subs
  has_many :comments
  has_many :votes, as: :votable


  has_many :subs,
  through: :post_subs

  belongs_to :author,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: "User"

  def comments_by_parent_id
    hash = Hash.new {|h,k| h[k]= [] }
    self.comments.each do |comment|
      hash[comment.parent_comment_id] << comment
    end
    hash
  end

end

redditclone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :not_logged_in?, only: [:edit, :update, :new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @all_comments = @post.comments.includes(:author)
    @comments_by_parent_id = @post.comments_by_parent_id
  end

  def edit
    @post = Post.find(params[:id])
    if current_user_.id == @post.user_id
      render :edit
    else
      flash[:errors] = ["not author of the post"]
      redirect_to sub_url(@post.sub)
    end
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @sub = @post.sub
    if @post
      @post.destroy
    end
    redirect_to subs_url
  end

  def upvote
    @post = Post.find(params[:id])
    @post.votes.create(value:1)
    redirect_to post_url(@post)
  end

  def downvote
    @post = Post.find(params[:id])
    @post.votes.create(value:-1)
    redirect_to post_url(@post)
  end

  private

  def post_params
    params.require(:post).permit(:title,:content,:user_id, sub_ids: [])
  end
end

redditclone/app/helpers/posts_helper.rb
module PostsHelper
end

redditclone/app/views/posts/_comment.html.erb
<% @comments_by_parent_id.each do |childkey, childval| %>
  <%if c1.id == childkey %>
  <ul>
    <li>
      <% childval.each do |c2| %>

        <h4><%= link_to c2.content, comment_url(c2) %> </h4>
        (<%= c2.votes.sum(:value) %>)
        by <%= c2.author.username %>
        created_at <%= c2.created_at %>

        <%= render "comment", c1:c2  %>

      <% end %>

    </li>
  </ul>
  <% end %>
<% end %>

redditclone/app/views/posts/edit.html.erb
<h1>Edit post!</h1>

<form action="<%=posts_url%>" method="post">

  <%= auth_token %>

  <input type="hidden" name="_method" value="patch">

  <label>Title
    <input type="text" name="post[title]">
  </label>
  <br>
  <label>Content
    <input type="text" name="post[content]">
  </label>
  <br></br>

  <input type="hidden" name="post[sub_ids][]" value="">

  <% Sub.all.each do |sub| %>
    <label > <%=sub.title%>
      <input type="checkbox"
              name="post[sub_ids][]"
              value="<%=sub.id%>"
              <%="checked" if @post.sub_ids.include?(sub.id) %>>
    </label>
    <br>
  <% end %>

  <input type="submit" value="Edit Post!">

</form>

redditclone/app/views/posts/new.html.erb
<h1>Create a post!</h1>

<form action="<%=posts_url%>" method="post">

  <%= auth_token %>
  <label>Title
    <input type="text" name="post[title]">
  </label>
  <br>
  <label>Content
    <input type="text" name="post[content]">
  </label>
  <br></br>

  <input type="hidden" name="post[sub_ids][]" value="">

  <% Sub.all.each do |sub| %>
    <label > <%=sub.title%>
      <input type="checkbox"
              name="post[sub_ids][]"
              value="<%=sub.id%>"
              <%="checked" if @post.sub_ids.include?(sub.id) %>>
    </label>
    <br>
  <% end %>

  <input type="submit" value="Create Post!">

</form>

redditclone/app/views/posts/show.html.erb
<h1>
  <%=@post.title%>
  (<%= @post.votes.sum(:value) %>)
</h1>

<div class="border">
  <h3> content </h3>
  <%=@post.content%>
  <%= button_to "Upvote", upvote_post_url %>
  <%= button_to "Downvote", downvote_post_url %>
</div>

<br></br>

<%= link_to "Make New Post!", new_post_url %>
<br>
<% if current_user && current_user.id == @post.user_id %>
  <%= link_to "Edit Sub", edit_post_url %>
<% end %>

<h3>Associated Subs for <%=@post.title%></h3>
<ul>
  <%@post.subs.each do |sub|%>
  <li>
    <%=link_to sub.title, sub_url(sub)%>
  </li>
  <% end %>
</ul>

<h3>  <%= link_to "Add a Comment to this Post!", new_post_comment_url(post_id: @post.id)  %> </h3>

<h1>Comments!</h1>


<%@comments_by_parent_id[nil].each do |c1|%>

    <h4><%= link_to c1.content, comment_url(c1) %></h4>
    (<%= c1.votes.sum(:value) %>)
    by <%= c1.author.username %>
    created_at <%= c1.created_at %>

    <%= render "comment", c1: c1, comments_by_parent_id: @comments_by_parent_id %>

<% end %>